apiVersion: v1
kind: ServiceAccount
metadata:
  name: udp-mux-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/version: {{ .Values.udpmuxVersion }}
{{ .Values.labels | toYaml | indent 4 }}
automountServiceAccountToken: false
